global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus-observer'
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: 'app'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['app:8000']
  - job_name: 'the-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['the-app:5060']
  - job_name: 'loki-observer'
    scrape_interval: 5s
    static_configs:
      - targets: ['loki:3100']

